### ISSUE TITLE
Examples of mixed type expressions

### ISSUE THREAD

**Issue by DavidAntliff** [foonathan/type_safe#101]
Thanks for the library. I'm hoping it will be useful to my projects.

Can you provide some brief examples on how to combine multiple mixed types in expressions, please?

For example, consider a value `w` of strong type `Angle` (float) divided by `c`, of a strong type `Count` (unsigned), the intention being to divide an angle into `c` equal parts, each of which is an `Angle`.

```
struct Angle : ts::strong_typedef<Angle, float>,
               ts::strong_typedef_op::floating_point_arithmetic<Angle> {
    using strong_typedef::strong_typedef;
};

struct Count : ts::strong_typedef<Count, unsigned int>,
               ts::strong_typedef_op::integer_arithmetic<Count> {
    using strong_typedef::strong_typedef;
};

int main() {
    Count c(5u);
    Angle w(360.0);

    Angle a(w / c);  // <--- this doesn't compile
}
```

What's the intended way to handle this? Should both the wrapped values of `w` be narrowed in some way to complete the division? This seems to bypass the usefulness of strong types. Or should the user define an `operator/(Angle &, Count &)`?

How should this be scaled if there are multiple strong `Count` types (for counting different things) - does this require a user-defined operator for every single combination used?

Is there (or could there be?) a mechanism to automatically create these mixed operators?

**Comment by foonathan** [comment]
There are `mixed_OP<StrongTypedef, T>` for `strong_typedef OP  t` and `t OP strong_typedef`, and `mixed_OP_noncommutative<StrongTypedef, T>` for `strong_typedef OP t`.

In your case, you'd want `Angle` to inherit from `mixed_division_noncommutative<Angle, Count>`.

**Comment by DavidAntliff** [comment]
Thank you. For others finding this issue, define Count first, then:

```
struct Angle : ts::strong_typedef<Angle, float>,
               ts::strong_typedef_op::floating_point_arithmetic<Angle>,
               ts::strong_typedef_op::mixed_division_noncommutative<Angle, Count> {  // enables Angle / Count
    using strong_typedef::strong_typedef;
};
```
