### ISSUE TITLE
No ts::float or ts::double types

### ISSUE THREAD

**Issue by Xenoamor** [foonathan/type_safe#102]
There are no `ts::float` or `ts::double` types available. There are `ts::float_t` and `ts::double_t` but these are not guaranteed to be of the same size.

[... float_t and double_t are floating types **at least as wide** as float and double](https://en.cppreference.com/w/c/numeric/math/float_t)

**Comment by foonathan** [comment]
I think I did that on purpose, but don't remember the exact rationale anymore. Would you want a `ts::float_`/`ts::double_`?

**Comment by foonathan** [comment]
Oh, btw @Xenoamor, I think you commented on some issue, but I can't find it anymore...

**Comment by Xenoamor** [comment]
Up to you really :) I'm working on an embedded system so I just tweaked them for my own use

I think the issue you were referring to might have been #54

**Comment by foonathan** [comment]
I think I'll just keep it that way then, but thanks for pointing it out.
