### ISSUE TITLE
Integrate checked arithmetics with equal precedence

### ISSUE THREAD

**Issue by philipp2100** [foonathan/type_safe#106]
You wrote [recently](https://github.com/foonathan/type_safe/issues/105#issuecomment-565075757) that you don't want `checked_arithmetic` by default, since this is in the first instance a library for type safety. I understand that, and probably checked arithmetic on unsigned types might also introduce errors.
However, since safe arithmetics are a closely related and important issue, I think they should be available with equal precedence, e.g. to make use of the literal operators to get types with checked arithmetics. This should be a simple change, like creating a new macro `TYPE_SAFE_ARITHMETIC_CHECKED`.
If you want, I can make a PR.

**Comment by foonathan** [comment]
Fair enough, I'll merge a PR that modifies the type aliases (but not the template defaults).

**Comment by philipp2100** [comment]
Great! :)
