### ISSUE TITLE
Add custom views of C++ objects in the debugger using the Natvis framework

### ISSUE THREAD

**Issue by NN---** [foonathan/type_safe#110]
This makes type_safe types like ts::compact_optional to be nicely presented in the debugger.

For more information check here:
https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019
https://code.visualstudio.com/docs/cpp/natvis
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/native-debugger-objects-in-natvis

**Comment by foonathan** [comment]
I don't use Windows, so I am not going to do that. I'll merge a PR, however.
