### ISSUE TITLE
abs() shouldn't change type (or handle min correctly)

### ISSUE THREAD

**Issue by philipp2100** [foonathan/type_safe#113]
The fact that abs(signed) returns unsigned limits its usability, for example one isn't able to freely mix expressions involving abs() with other values. It is also counter-intuitive, as 
std::abs(), as well as various boost::abs(), don't behave that way. It could even be a source off errors, when one passes the result of abs().get() to other functions or uses it in another way.
Since there's also a version for built-in types, I even more so think that abs() should behave like std::abs() (though they are in different namespaces, so having a change of behavior depending on which headers are included would arguably be a misuse of `using`). 

Is there any benefit from having it this way? I couldn't find any documentation on this.
Generally this seems to encourage what most consider bad practice (the mix of signed an unsigned type). Since you wrote a whole library to address this issue, I doubt that that's your intention or you are not aware of it. :) If you are [also](https://github.com/fish-shell/fish-shell/issues/3493) advocating for the use of unsigned types mostly, I still think there would be better ways to cover these use cases.
After all, a conversion is always possible with make_unsigned() but the way back is far less trivial, if I see correctly.

That brings us to INT_MIN. Since it is not supported as of now, one could easily do make_signed(abs()) (which would still require branching in templated code that should work with both safe and built-in types). However, I think it should at least be documented. If the return type stays unsigned, it could also be made work (i.e., returning the correct value, breaking make_signed(abs)). The version for safe types also doesn't use the chosen arithmetic policy (which more accurately is an issue of `operator-`).

**Comment by foonathan** [comment]
> Is there any benefit from having it this way?

I wanted to have the following conversion:

1. `unsigned -> signed`, getting an error if the unsigned value exceeds the signed range.
2. `signed -> unsigned`, getting an error if the value is positive.
3. `signed -> unsigned`, converting the absolute value.

I named 1. `make_signed`, 2. `make_unsigned`, and 3. `abs`. My general philosophy was to express preconditions in types. The postcondition of abs is a positive value, so I express that in a positive-only type.

> That brings us to INT_MIN. Since it is not supported as of now

What do you mean here exactly?

**Comment by philipp2100** [comment]
I see that such conversions can be useful. Maybe the function could be named differently, such as `abs_unsigned()`?

It's a widely adopted convention, not only inside C/C++ but also in other languages, to have `abs()` return the same type as its input. It is also widely considered bad practice to express non-negativity with an unsigned type. The main reason for both is presumably that this leads to mixing signed and unsigned types in expressions, which is bad.

In the INT_MIN case, `abs()` would attempt to return `make_unsigned(-INT_MIN)`, so that doesn't work.

**Comment by foonathan** [comment]
> I see that such conversions can be useful. Maybe the function could be named differently, such as abs_unsigned()?

I don't see how I could change it now, without breaking a lot.

> It's a widely adopted convention, not only inside C/C++ but also in other languages, to have abs() return the same type as its input. It is also widely considered bad practice to express non-negativity with an unsigned type. The main reason for both is presumably that this leads to mixing signed and unsigned types in expressions, which is bad.

The goal of my library was to develop tools to express such conditions with the type system. For that, I've developed the ts::integer to make mixing signed/unsigned types better. The fact that abs changes the type reflects that philosophy.

> In the INT_MIN case, abs() would attempt to return make_unsigned(-INT_MIN), so that doesn't work.

Thank you, I've changed the implementation of  operator-() to use the policy, which is then able to catch overflow. As such, I'm closing this issue.
