### ISSUE TITLE
How to constraint a semantic type?

### ISSUE THREAD

**Issue by FlorianWolters** [foonathan/type_safe#119]
I'm currently evaluating "type_safe" and consider to include it into a software project. The type safety features for primitive types look awesome and I also think that the two concepts "semantic types" and "constrained types" can improve our code.

There is at least one thing I can't figure out on my own: How can one define constraints for a semantic type?

Consider the following simple semantic type (no constraints yet):

    struct Percent final
        : type_safe::strong_typedef<Percent, std::uint32_t>,
          type_safe::strong_typedef_op::output_operator<Percent>,
          type_safe::strong_typedef_op::equality_comparison<Percent>,
          type_safe::strong_typedef_op::relational_comparison<Percent> {
      using strong_typedef::strong_typedef;
    };

I know that I can declare a constrained type with a type alias as follows.

    using PercentInt =
        type_safe::bounded_type<std::uint32_t,
                                true,
                                true,
                                std::integral_constant<std::uint32_t, 0>,
                                std::integral_constant<std::uint32_t, 100>>;

But this isn't good enough! I would like to combine the semantic type `Percent` with the constraint.

I couldn't find any mention of this feature in blog posts or the `examples` directory.

1. Is it generally possible to combine semantic types with constrained types with "type_safe"?
2. How to declare a constraint, e.g. a bounded constraint (value 0-100, inclusive) for the `Percent` type?

**Comment by foonathan** [comment]
Have you tried `using PercentInt = ype_safe::bounded_type<Percent, ...>`? That should work.

**Comment by FlorianWolters** [comment]
Yes, I've tried that, but maybe I'm too stupid to declare the type correctly.

All the following type alias declarations do not work:

    using PercentBounded =
        type_safe::bounded_type<Percent,
                                true,
                                true,
                                std::integral_constant<std::uint32_t, 0>,
                                std::integral_constant<std::uint32_t, 100>>;
                                
    using PercentBounded =
        type_safe::bounded_type<Percent,
                                true,
                                true,
                                std::integral_constant<Percent, 0>,
                                std::integral_constant<Percent, 100>>;
                                
    // This is obvious, because a type is expected as the 4th and 5th argument.
    using PercentBounded =
        type_safe::bounded_type<Percent,
                                true,
                                true,
                                Percent{0},
                                Percent{100}>;

But besides that: Is is required to declare a separate type (with a different API) to achieve what I want to achieve?

To be more explicit: I ask for a semantic type that has one or more constraints that can be declared as Mixins via CRTP.

The client usage should always be as follows:

    // Constrained type with range constraint.
    example::Percent const percent{0U};   // valid!
    example::Percent const percent{100U}; // valid!
    example::Percent const percent{101U}; // invalid!

I've had the hope that a declaration such as one of the following would be possible:

This doesn't compile (can't construct an instance):

    struct Percent
        : type_safe::strong_typedef<Percent, std::uint32_t>,
          type_safe::strong_typedef_op::output_operator<Percent>,
          type_safe::strong_typedef_op::equality_comparison<Percent>,
          type_safe::strong_typedef_op::relational_comparison<Percent>,
          type_safe::bounded_type<std::uint32_t,
                                  true,
                                  true,
                                  std::integral_constant<std::uint32_t, 0>,
                                  std::integral_constant<std::uint32_t, 100>> {
      using strong_typedef::strong_typedef;
    };

This does compile, but the constraint is not activated/checked:

    struct Percent : type_safe::strong_typedef<Percent, std::uint32_t>,
                     type_safe::strong_typedef_op::output_operator<Percent>,
                     type_safe::strong_typedef_op::equality_comparison<Percent>,
                     type_safe::strong_typedef_op::relational_comparison<Percent>,
                     type_safe::constraints::bounded<
                         std::uint32_t,
                         true,
                         true,
                         std::integral_constant<std::uint32_t, 0>,
                         std::integral_constant<std::uint32_t, 100>> {
      using strong_typedef::strong_typedef;
    };

**Comment by foonathan** [comment]
Ah, you need `mixed_relation_comparison<Percent, int>`, then the first typedef should work.

**Comment by FlorianWolters** [comment]
Mhh... Then I assume the following is **not** possible:
- preferable: Declare one semantic type with one or more constraints (`Percent` only).
- "ok": Add one or more constraints to an already defined semantic type by another type. (e.g. `PercentUnconstrained` and `Percent`, the former is the semantic type and the latter is the constrained semantic type).

`mixed_relation_comparison<Percent, int>` reads wrong to me: I don't want to compare `Percent` with `int`, which would loosen the type system. I would like to to constraint `Percent` to the interval `[Percent{0}, Percent{100}]` (not `int`).

I ask more more direct: Can you provide **one** declaration for a strong `Percent` type with the interval `[Percent{0}, Percent{100}]` together with, e.g. `type_safe::strong_typedef_op::equality_comparison<Percent>`?

**Comment by foonathan** [comment]
> Mhh... Then I assume the following is **not** possible:
> 
>     * preferable: Declare one semantic type with one or more constraints (`Percent` only).

This is not possible, correct.

>     * "ok": Add one or more constraints to an already defined semantic type by another type. (e.g. `PercentUnconstrained` and `Percent`, the former is the semantic type and the latter is the constrained semantic type).

This is possible. Either in the way I've shown you or using `ts::constrained_type<PercentUnconstrained, MyPercentConstrained>`, where `MyPercentConstrained` is a function object type, like this one: https://github.com/foonathan/type_safe/blob/main/include/type_safe/constrained_type.hpp#L589

Both options are equivalent, `ts::bounded_type` is just an alias for `ts::constrained_type`.

> 
> `mixed_relation_comparison<Percent, int>` reads wrong to me: I don't want to compare `Percent` with `int`, which would loosen the type system. I would like to to constraint `Percent` to the interval `[Percent{0}, Percent{100}]` (not `int`).

Yeah, this is a bit messy. In C++20 you should be able to use `std::integral_constant<Percent, 100>` as the bounds directly and don't need the `int` comparison.

> I ask more more direct: Can you provide **one** declaration for a strong `Percent` type with the interval `[Percent{0}, Percent{100}]` together with, e.g. `type_safe::strong_typedef_op::equality_comparison<Percent>`?

See above

Note that in `ts::constrained_type` is a bit unergonomic, as you need to go to the pointer interface: there is no generic way to do it otherwise. For a hypothetical `Percent` type you know all the operations you want to do on `Percent`, so you could manually implement a nicer interface that does the check after each arithmetic operation.

**Comment by FlorianWolters** [comment]
Thanks for the reply. What exactly do you mean with the following sentence?

> Ah, you need `mixed_relation_comparison<Percent, int>`, then the first typedef should work.

Do you mean my approach 1 below? The "best" I could come up using the "constraint types" feature of `type_safe` is the following.

1. Using `type_safe::strong_typedef_op::mixed_relational_comparison`.

        struct PercentMixedUnconstrained final
            : type_safe::strong_typedef<PercentMixedUnconstrained, std::uint32_t>,
              type_safe::strong_typedef_op::output_operator<PercentMixedUnconstrained>,
              type_safe::strong_typedef_op::equality_comparison<
                  PercentMixedUnconstrained>,
              type_safe::strong_typedef_op::relational_comparison<
                  PercentMixedUnconstrained>,
              type_safe::strong_typedef_op::
                  mixed_relational_comparison<PercentMixedUnconstrained, std::uint32_t>,
              type_safe::strong_typedef_op::integer_arithmetic<
                  PercentMixedUnconstrained> {
          using strong_typedef::strong_typedef;
        };

        using PercentMixedConstrained =
            type_safe::bounded_type<PercentMixedUnconstrained,
                                    true,
                                    true,
                                    std::integral_constant<std::uint32_t, 0>,
                                    std::integral_constant<std::uint32_t, 100>>;

    Usage:

        // Issue 1 : Too complex API! I would like to use `PercentMixedConstrained`
        // in the same way as `PercentMixedUnconstrained`.
        PercentMixedConstrained const percent{PercentMixedUnconstrained{50}};
        std::cout << percent.get_value() << '\n';
        std::cout << "EqualityComparison: "
                  << (percent.get_value() == PercentMixedUnconstrained{50}) << '\n';
        std::cout << "Addition: "
                  << (percent.get_value() + PercentMixedUnconstrained{50}) << '\n';

2. Using `type_safe:::constrained_type`

        struct PercentUnconstrained final
            : type_safe::strong_typedef<PercentUnconstrained, std::uint32_t>,
              type_safe::strong_typedef_op::output_operator<PercentUnconstrained>,
              type_safe::strong_typedef_op::equality_comparison<PercentUnconstrained>,
              type_safe::strong_typedef_op::relational_comparison<PercentUnconstrained>,
              type_safe::strong_typedef_op::integer_arithmetic<PercentUnconstrained> {
          using strong_typedef::strong_typedef;
        };

        struct PercentConstraint {
          auto operator()(PercentUnconstrained const& percent) const -> bool {
            return percent <= PercentUnconstrained{100};
          }
        };

        using PercentConstrained =
            type_safe::constrained_type<PercentUnconstrained, PercentConstraint>;

    Usage:

        // Issue 1: Too complex API! I would like to construct `PercentConstrained`
        // from the underlying type of `PercentUnconstrained`.
        PercentConstrained const percent{PercentUnconstrained{75}};
        // Issue 2 : Too complex API, I would like to use `PercentConstrained` in
        // the same way as `PercentUnconstrained`.
        std::cout << percent.get_value() << '\n';
        std::cout << "Addition: " << percent.get_value() + PercentUnconstrained{20} << '\n';

**But...** Then I noticed that I really don't need the "constraint type" feature at all.

The solution is pretty simple and does exactly what I want. Note that exceptions are allowed and used in our code base and are superior to assertions for strong types, imo.

    // Good: Simple declaration using **one** public type!
    struct Percent : type_safe::strong_typedef<Percent, std::uint32_t>,
                     type_safe::strong_typedef_op::equality_comparison<Percent>,
                     type_safe::strong_typedef_op::relational_comparison<Percent>,
                     type_safe::strong_typedef_op::integer_arithmetic<Percent>,
                     type_safe::strong_typedef_op::output_operator<Percent> {
      explicit Percent(std::uint32_t const value)
          : type_safe::strong_typedef<Percent, std::uint32_t>{value} {
        if (value > 100) {
          throw std::runtime_error{
              "The value of 'Percent' must be in the interval [0,100]."};
        }
      }
    };

  Usage:

    // Good: API is nice and clean (domain model can be easily added to the
    // `struct` or `class`.
    Percent const percent{50};
    std::cout << percent << '\n';
    std::cout << "EqualityComparison: " << (percent == Percent{50}) << '\n';
    std::cout << "GreaterThanComparison: " << (percent > Percent{49}) << '\n';
    std::cout << "LessThanOrEqualComparison: " << (percent <= Percent{51}) << '\n';

    std::cout << "Addition: " << (percent + Percent{50}) << '\n';
    std::cout << "Subtraction: " << (percent - Percent{50}) << '\n';
    std::cout << "Multiplication: " << (percent * Percent{2}) << '\n';
    std::cout << "Division: " << (percent / Percent{50}) << '\n';

    // Good: Exceptions on invariant violation. This also checks the invariants
    // when applying arithmetic operations.
    try {
      Percent{101};
    } catch (std::exception const& ex) {
      std::cerr << ex.what() << '\n';
    }

    // Good: This also checks the invariants when using arithmetic operations.
    try {
      percent + Percent{51};
    } catch (std::exception const& ex) {
      std::cerr << ex.what() << '\n';
    }

    try {
      percent - Percent{51};
    } catch (std::exception const& ex) {
      std::cerr << ex.what() << '\n';
    }

By using this pattern, the `type_safe` library may be a candidate for our code (with a usage restriction of its features).

1. The declaration for the type `Percent`is reasonable simple (without much boilerplate).
2. Invariants are checked where they belong (in the constructor). I think this could be improved with a small utility library that simplifies/unifies the checks and exception throw (e.g. uniform messages).
3. Developers do not need to know much about the `type_safe` library, except for the `type_safe::strong_typedef*` stuff.

`Percent` is now an opaque strong type with (almost) the same API as a `std::uint_32_t`. Nice!

Do you see any disadvantages using this approach? I certainly need to perform some additional tests, but this looks pretty nice.

**Comment by foonathan** [comment]
> Do you mean my approach 1 below? The "best" I could come up using the "constraint types" feature of `type_safe` is the following.
> 
>     1. Using `type_safe::strong_typedef_op::mixed_relational_comparison`.

Yes, this is what I meant.
>        
>        Usage:
>        ```
>         // Issue 1 : Too complex API! I would like to use `PercentMixedConstrained`
>         // in the same way as `PercentMixedUnconstrained`.
>         PercentMixedConstrained const percent{PercentMixedUnconstrained{50}};
>         std::cout << percent.get_value() << '\n';
>         std::cout << "EqualityComparison: "
>                   << (percent.get_value() == PercentMixedUnconstrained{50}) << '\n';
>         std::cout << "Addition: "
>                   << (percent.get_value() + PercentMixedUnconstrained{50}) << '\n';
>        ```

Yeah, that's what I alluded to with "Note that in ts::constrained_type is a bit unergonomic, as you need to go to the pointer interface: there is no generic way to do it otherwise."

> 
>     2. Using `type_safe:::constrained_type`

Yes, that is the other possibility, again with the unergonomic interface.

> 
> Do you see any disadvantages using this approach? I certainly need to perform some additional tests, but this looks pretty nice.

There is one potential problem with the approach, e.g. `(a + b) / 2` can lead to an early assertion/exception even though the final value is fine. The version that uses constrained types does not suffer from this problem, as the constrained is only checked when the modifier is destroyed at the end.

> Developers do not need to know much about the type_safe library, except for the type_safe::strong_typedef* stuff.

Yeah, that's certainly the best part of type_safe. Other facilities that are still useful with C++20 and you might want to check out are `ts::object_ref<T>` (a non-null pointer) and `ts::flag_set<Enum>` (better enums as flag sets).

**Comment by FlorianWolters** [comment]
> There is one potential problem with the approach, e.g. `(a + b) / 2` can lead to an early assertion/exception even though the final value is fine. The version that uses constrained types does not suffer from this problem, as the constrained is only checked when the modifier is destroyed at the end.

Ugh... Gotcha. Seems I've to come up with something smarter then.

Anyway: Thanks for all your responses and thanks for the awesome library. I will further play around with it before integrating it in our production code. But it looks pretty good.

**Comment by foonathan** [comment]
> Ugh... Gotcha. Seems I've to come up with something smarter then.

I mean, there is no real solution if you want to keep the arithmetic operation syntax. You could use proxy type, such that `a + b` gives you a `PercentProxy` that is implicitly convertible to `Percent` at which the point the invariant is checked, but this breaks `auto`.

Note that in principle, the same issue applies to plain integers, although the issue is more rare there. It must just train your team to be more careful about integer overflow...
