### ISSUE TITLE
`constrained_type`'s `Constraint` and `Verifier` requirements and effects

### ISSUE THREAD

**Issue by johelegp** [foonathan/type_safe#12]
`constrained_type`'s documentations specifies that
> _Requires:_ ... `Constraint` must be a functor of type `bool(const T&)` ...

However, it is unclear what else is expected of this type. In particular:
* It is used as a base, so it can't be final.
* Some functions require it to be
  - `DefaultConstructible` (this is actually on the call site)
  - `MoveConstructible`
  - `CopyConstructible`

Those same functions don't document in the _Throws:_ what happens if an operation on a `Constraint` throws, nor is it accounted for in the `noexcept` conditions.

---

Looking at other definitions that use, or are intended to be used with `constrained_type`, in particular, `null_verifier`, `tagged_type` and `owner`, it seems that other requirements on `Constraint` (apart from those listed above) and `Verifier` depend on how these two interact.

To me, it feels weird that suddenly the requirements on `Constraint` and `Verifier` don't apply. Perhaps it would be a nice idea to add a note that a `constrained_type` with a `null_verifier` is treated as a special case, so that the users can rely on the actual requirements.

**Comment by foonathan** [comment]
You are right.

It would be better if `constrained_type` only documents that it requires inheritance and move constructor, and document the predicate requirement in the verifier.
