### ISSUE TITLE
Linker error in specific circumstances with Doctest

### ISSUE THREAD

**Issue by ratiotile** [foonathan/type_safe#121]
I'm getting a strange error when constructing a strong_typedef type in a struct initializer, inside a lambda, inside a doctest TEST_CASE.

```
3>LibraryB.lib(Opponent.obj) : error LNK2019: 
unresolved external symbol "public: __thiscall A::PlayerId::PlayerId(int &&)" (??0PlayerId@A@@QAE@$$QAH@Z) 
referenced in function "void __cdecl _DOCTEST_ANON_SUITE_2::_DOCTEST_ANON_FUNC_3(void)" (?_DOCTEST_ANON_FUNC_3@_DOCTEST_ANON_SUITE_2@@YAXXZ)
```

Here is my usage of strong_typedef:
``` c++
struct PlayerId
    : type_safe::strong_typedef<PlayerId, int>
    , type_safe::strong_typedef_op::equality_comparison<PlayerId>
    , type_safe::strong_typedef_op::relational_comparison<PlayerId>
    , type_safe::strong_typedef_op::output_operator<PlayerId>
  {
    using strong_typedef::strong_typedef;
  };
```

This is the code that causes the error:
``` c++
TEST_SUITE("Opponent") {
  using namespace A;

  struct Foo {
    PlayerId id;
  };
 
  TEST_CASE("Linker Error") {
    auto bar = []() {
      auto f = Foo{
        .id = PlayerId(1),
      };
    };
    bar();
  }

}
```

I've simplified my code to a minimal reproduction here: https://github.com/ratiotile/typesafe_link_error_repro

**Comment by foonathan** [comment]
I think the issue is that you're having a test case inside another test case. I don't think that is supported.

**Comment by ratiotile** [comment]
TEST_CASE is allowed inside a TEST_SUITE according to documentation: https://github.com/onqtam/doctest/blob/master/doc/markdown/testcases.md#test-suites

**Comment by ratiotile** [comment]
I found that I can work around this error by explicitly creating an instance of the strong_typedef type in the implementation file of the object referenced in the linker error. It's strange that this link error only happens in the case of a move constructor call.

**Comment by foonathan** [comment]
I cannot reproduce the issue with clang and gcc on Linux, and I don't have a dev machine running Windows. What happens when you manually `= default` a move constructor (and the other ones) in `PlayerId`?

**Comment by ratiotile** [comment]
Adding defaulted constructors doesn't work.
However, adding a move constructor for int works: 
```c++
explicit PlayerId(int&& i) : type_safe::strong_typedef<PlayerId, int>(i) {};
```
I thought it's weird to move an int, but just `PlayerId(int i)` doesn't work.

**Comment by foonathan** [comment]
This feels a lot like a compiler bug and/or an issue with doctest. I'm not sure what I can do on my end.
