### ISSUE TITLE
Stateless `bounded` constraint

### ISSUE THREAD

**Issue by johelegp** [foonathan/type_safe#13]
Have you considered having a `bounded` constraint which doesn't store the bounds as data members, but in the template arguments instead?

I think this is achievable for arbitrary literal types. The bound values can be encoded in types, as done in `boost::hana`.

The current behaviour of the bounds being dynamic could be indicated by a special value, as done with the `dynamic_extent` in the proposed [`span`](http://wg21.link/p0122). This could be done with an `Optional` or `Variant` that stores the arbitrary literal type value if the bound is static.

I am not sure how feasible this is with C++11, which this library targets.

**Comment by johelegp** [comment]
I've made a C++11-compatible implementation of this idea in [johelegp:stateless_bounded_constraint](/johelegp/type_safe/tree/stateless_bounded_constraint). The difference is that the "special value" is actually the empty class `dynamic_bound`, and anything else should be a `boost::hana::Constant`.

Here's an example:
```C++
#include <type_traits>
#include <iostream>
#include <type_safe/bounded_type.hpp>
namespace ts = type_safe;

template <int X>
using ic = std::integral_constant<int,X>;

int main()
{
    std::cout << "sizeof(ts::bounded_type<int,true,true>) == "
              << sizeof(ts::bounded_type<int,true,true>) << '\n'
              << "sizeof(ts::bounded_type<int,true,true,ic<0>,ic<10>>) == "
              << sizeof(ts::bounded_type<int,true,true,ic<0>,ic<10>>) << '\n';
}
```
On my machine, this outputs
```
sizeof(ts::bounded_type<int,true,true>) == 12
sizeof(ts::bounded_type<int,true,true,ic<0>,ic<10>>) == 4
```

**Comment by foonathan** [comment]
You are right, that was a stupid oversight when I wrote that constraint.
I support the idea of compile time bounds.
