### ISSUE TITLE
Make is_strong_typedef public

### ISSUE THREAD

**Issue by BrukerJWD** [foonathan/type_safe#130]
Currently, `is_strong_typedef` is an implementation detail in `type_safe::type_safe_op::detail`:
https://github.com/foonathan/type_safe/blob/2809f17824e1c6b61aa710015bba73e3d0b26728/include/type_safe/strong_typedef.hpp#L207

For me and my SFINAE approach it would be of help to have `is_strong_typedef` (and a `is_strong_typedef_v`) in the (public) `type_safe` namespace.

**Comment by foonathan** [comment]
Sure, can you do a PR?

**Comment by BrukerJWD** [comment]
Sure :) I'm going to need some time, though.
