### ISSUE TITLE
CMake installation is not architecture independent

### ISSUE THREAD

**Issue by jeromehue** [foonathan/type_safe#136]
When type_safe is installed with CMake the standard way (such as `cmake -S . -B build && cmake --install build`,  the generated type_safe-config-version.cmake file contains the following lines :
```
# if the installed project requested no architecture check, don't perform the check
if("FALSE")
  return()
endif()

# if the installed or the using project don't have CMAKE_SIZEOF_VOID_P set, ignore it:
if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
  return()
endif()

# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
  math(EXPR installedBits "8 * 8")
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```
which do exactly what is indicated, an architecture check (In this example, it won't accept to include type_safe for a 32 bit target).
Because type_safe is header-only, it is arch independent, and this should be enforced in CMakeLists.txt.
There are two ways to achieve this goal :
### Before CMake 3.14
Adding `set(CMAKE_SIZEOF_VOID_P "")` before `write_basic_package_version_file` in CMakeLists.txt, line 113.
https://github.com/foonathan/type_safe/blob/e9da2dcaeb58c40dcadd1bfaa629b4202a666068/CMakeLists.txt#L113-L117
See [this similar issue](https://github.com/catchorg/Catch2/issues/1660) for more details.

### After (and including) CMake 3.14
CMake provide an `ARCH_INDEPENDENT` argument to add to `write_basic_package_version_file`. 
Documentation is available here : https://cmake.org/cmake/help/v3.14/module/CMakePackageConfigHelpers.html#command:write_basic_package_version_file.
Our function will look like this : 
```
write_basic_package_version_file(
  ${CMAKE_CURRENT_BINARY_DIR}/type_safe-config-version.cmake
  VERSION 0.2.2
  COMPATIBILITY SameMajorVersion
  ARCH_INDEPENDENT
)
```
and the resulting type_safe-config-version-file.cmake will now contains :
```
# if the installed project requested no architecture check, don't perform the check
if("TRUE")
  return()
endif()
```

**Comment by jeromehue** [comment]
A similar example in another header only library https://github.com/ETLCPP/etl/pull/534

**Comment by foonathan** [comment]
Sounds good. Can you do a PR with the option before 3.14?
