### ISSUE TITLE
Unintuitive error messages with ts::boolean

### ISSUE THREAD

**Issue by mariobadr** [foonathan/type_safe#14]
Suppose I have a class that uses a `ts::strong_typedef` with `equality_comparison`:

```C++
struct memory_address :
  type_safe::strong_typedef<memory_address, type_safe::uint32_t>,
  type_safe::strong_typedef_op::equality_comparison<memory_address>,
  type_safe::strong_typedef_op::output_operator<memory_address>
{
  using strong_typedef::strong_typedef;
};

class example1 {
public:
  example1(memory_address const obj);
private:
  memory_address const object;

  friend bool operator==(example1 const &, example1 const &);
};
```

The following will not compile (because it cannot convert `type_safe::boolean` to `bool` - I am aware I could use `equality_comparison<memory_address, bool>` instead):

```C++
inline bool operator==(example1 const & lhs, example1 const & rhs)
{
  return lhs.object == rhs.object;
}
```

However, in a second example class we add another comparison using type_safe::integer, which will compile just fine:

```C++
class example2 {
public:
  example2(memory_address const obj, unsigned const count);
private:
  memory_address const object;
  type_safe::integer<unsigned> count;

  friend bool operator==(example2 const &, example2 const &);
};

inline bool operator==(example2 const & lhs, example2 const & rhs)
{
  return lhs.object == rhs.object && lhs.count == rhs.count;
}
```

Should this not have also caused an error?

**Comment by foonathan** [comment]
The `&&` operator will trigger a contextual conversion to `bool`, so the `explicit operator bool` on `ts::boolean` is called which will make a `bool`, so it can be returned.

The only way to prevent that would be overloading `operator&&`, but... you know.
