### ISSUE TITLE
Fix or work around a probable MS compiler bug when using C++ 20 or above

### ISSUE THREAD

**Issue by davidhunter22** [foonathan/type_safe#142]
If you try to include certain header like optional.hpp when using the MS compiler with the language standard set to C++ 20 or above you get errors. An MS issue has been filed for this https://developercommunity.visualstudio.com/t/VS-22-174-templated-constructor-paramet/10202157. You can also look at https://godbolt.org/z/hMGz9bdMW.

I am not sure how to fix this as I am not sure how to fix or work around this. There are a few instances, all like
```
    basic_optional(
        T&& value,
        decltype(std::declval<storage>().create_value(std::forward<T>(value)), 0) = 0)
    {
        get_storage().create_value(std::forward<T>(value));
    }
```
which gives the error
`error C2065: 'value': undeclared identifier`
The code looks to me like a variant of SFINAE but I assume there is a reason the code does not use enable_if constructs.

AT the moment I would probably just def out the offending code as in
```
    basic_optional(
        #if defined(TYPE_SAFE_POSSIBLE_CL_BUG)
        T&& value )
        #else
        T&& value,
        decltype(std::declval<storage>().create_value(std::forward<T>(value)), 0) = 0)
        #endif
    {
        get_storage().create_value(std::forward<T>(value));
    }
```
but I am assuming that the code is there for a reason!!! 
Note the default would be the old code, this would allow me to make progrss on the standard library module stuff
Any suggestions welcome

**Comment by foonathan** [comment]
Can you try `decltype(std::declval<storage>().create_value(std::declval<T>()), 0) = 0)`?
