### ISSUE TITLE
std::aligned_storage_t are deprecated in C++23

### ISSUE THREAD

**Issue by davidhunter22** [foonathan/type_safe#144]
In C++ 23 [alignem ](std::aligned_storage_t) and is normally replace using things like alignas(T) std::byte t_buff[sizeof(T)].

alignas has been around since C++ 11 so I am assuming it is OK to just do a direct replacement rather than some ifdef allowing use of the old one

There are a couple of fairly diect replacement but one that I was unsure about
```
    template <typename... Types>
    struct aligned_union
    {
        static constexpr auto size_value      = detail::max(sizeof(Types)...);
        static constexpr auto alignment_value = detail::max(alignof(Types)...);

        using type = typename std::aligned_storage<size_value, alignment_value>::type;
    };
```
This seems to be a variant of std::aligned_union which is also deprecated in C++23. The most one to one replacement I can think of is
```
    template <typename... Types>
    struct aligned_union
    {
        static constexpr auto size_value      = detail::max(sizeof(Types)...);
        static constexpr auto alignment_value = detail::max(alignof(Types)...);

        struct type { alignas(alignment_value) std::byte data[size_value]; };
    };
```

but I have never used any form of alignmet stuff before. 

Note also things like 
```
    template <typename T, typename... Ts>
    constexpr const T& max(const T& t, const Ts&... ts)
```
would also appear to be just replicas of stuff available in the standard library.

**Comment by davidhunter22** [comment]
After a bit of reading the following seems cleaner
```
    template <typename... Types>
    struct alignas(Types...) aligned_union
    {
        std::byte data[ std::max(sizeof(Types)...)];
    };
```
Might fall foul of Hyrum's law though

**Comment by foonathan** [comment]
> This seems to be a variant of std::aligned_union which is also deprecated in C++23. 

IIRC, aligned_union wasn't available on some compilers initially.

> would also appear to be just replicas of stuff available in the standard library.

Not a variadic version.

> The most one to one replacement I can think of is

That one is actually the exact re-implementation of std::aligned_union, which is UB (and the reason aligned_union is deprecated). I think the best idea is to simply remove `::type` and use an aligned array instead with the values computed by`::size_value` and `::alignment_value`.
