### ISSUE TITLE
Invalid certificate for type_safe.foonathan.net

### ISSUE THREAD

**Issue by phethataka** [foonathan/type_safe#152]
> Firefox detected a potential security threat and did not continue to type_safe.foonathan.net.
> …
> Firefox does not trust this site because it uses a certificate that is not valid for type_safe.foonathan.net. The certificate is only valid for the following names: *.github.io, github.io, *.github.com, github.com, www.github.com, *.githubusercontent.com, githubusercontent.com
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by foonathan** [comment]
I think it is fixed now.
