### ISSUE TITLE
Documentation is missing description for some of the operation constraints

### ISSUE THREAD

**Issue by Jazzinghen** [foonathan/type_safe#157]
I know this sounds more like a "question" than an issue, but I did not find any way to get information on this so I think this might be an issue.
I have been trying to use `type_safe` to define a binary word datatype and I added multiple operations. One of them, `type_safe::strong_typedef_of::bitshift`, is defined as such:
```c++
template <class StrongTypedef, typename IntT>
    struct bitshift
{};
```
I have been trying to understand what the second template parameter, `IntT`, is, without results. I have been reading throughout the code and it seems like this definition is the only one that uses this pattern in the strong typedefs header, however I might have understood that the second parameter should limit the shift parameter type, however I am not 100% sure.
I think there should be a bit more documentation for this library (even just a bit more comments in the code) to make it more accessible.

**Comment by BrukerJWD** [comment]
I don't understand how this works, as `IntT` is not used anywhere else in the code.
It is the bitshit parameter type, though:

    struct foo
        : ts::strong_typedef<foo, int>
    {
        using strong_typedef::strong_typedef;
    };
    
    struct bar
        : ts::strong_typedef<bar, int>
        , ts::strong_typedef_op::output_operator<bar>
        , ts::strong_typedef_op::bitshift<bar, foo>
    {
        using strong_typedef::strong_typedef;
    };
    
    int main()
    {
        foo f(1);
        bar b(2);
        // b <<= 2; // does not compile
        b <<= foo(2);
        std::cout << '>' << b << '\n';
        return 0;
    }

**Comment by foonathan** [comment]
> It is the bitshit parameter type, though:

Yes.

> I don't understand how this works, as IntT is not used anywhere else in the code.

The macro `TYPE_SAFE_DETAIL_MAKE_OP_MIXED` generates `operator<<` taking a `bitshift<StrongTypedef, IntType>`, and uses `IntType` there to constrain the other parameter.

> I think there should be a bit more documentation for this library (even just a bit more comments in the code) to make it more accessible.

Yeah, but I'm no longer using standardese which the documentation is based on, and rewriting better docs is boring work that I don't really want to do... :D Feel free to ask questions, and I try to answer them quicker, sorry about that.
