### ISSUE TITLE
strong_typedef: control over default constructor behaviour

### ISSUE THREAD

**Issue by ngrodzitski** [foonathan/type_safe#158]
It would be nice to be able to avoid explicit default construction for `strong_typedef::value_`

https://github.com/foonathan/type_safe/blob/6ae2495bd9eafaa6d93b497a09f43a3d80141755/include/type_safe/strong_typedef.hpp#L54-L60

So that it would be possible to avoid unnecessary initialization when needed. (Here is an example: https://godbolt.org/z/49xMb4TEY).

**Comment by foonathan** [comment]
Part of the library design philosophy is safety, so I don't want to leave it uninitialized.
