### ISSUE TITLE
EqualityComparable and TotallyOrdered `constrained_type`

### ISSUE THREAD

**Issue by johelegp** [foonathan/type_safe#16]
Given that `constrained_type` is a wrapper for a `T`, it'd be very convenient if it modelled the `EqualityComparable` and `TotallyOrdered` concepts if `T` does. This relieves users from doing hack-arounds to get their comparisons done.

It should be type-safe, by default, to compare objects of the same `constrained_type` specialization.

Other considerations:
- Comparison with `const U& u`, if constructing the `constrained_type` from `u` is well-formed.
- Comparison with other `constrained_type` of `T`, regardless of their `Constraint` and `Verifier`.

**Comment by foonathan** [comment]
Yes, I agree. I was just too lazy to write it.

**Comment by johelegp** [comment]
Actually, the `Constraint` is also part of the value of a `constrained_type`, so it should be included in the comparisons too.

As an aid to the user, if the empty base optimization applies to the `Constraint` and it isn't `EqualityComparable` or `TotallyOrdered`, it could simply be left out of those comparisons.

What do you think?

**Comment by foonathan** [comment]
I've just added comparisons for constrained types where everything matches for now.
