### ISSUE TITLE
Add support for PlatformIO

### ISSUE THREAD

**Issue by meikjaeckle** [foonathan/type_safe#162]
Would it be ok for you, to add an `library.json` file to the your root directory to enable PlatformIO support.

It would look like similar to this one: [library.json](https://github.com/meikjaeckle/type_safe/commit/7a1bdfd0dbab77319c9111d16df29dc3e771f873).

Then I could use your repo directly and wouldn't need my copy: https://github.com/meikjaeckle/type_safe/tree/platformio

**Comment by foonathan** [comment]
I don't want to maintain non-standard package information, sorry.
