### ISSUE TITLE
User-defined literals don't perform overflow checks

### ISSUE THREAD

**Issue by sneves** [foonathan/type_safe#19]
One would expect that the following snippet would result in some kind of error, compile-time or otherwise:

```
#include <type_safe/types.hpp>

int main() {
  using namespace type_safe::literals;
  return (1234_u8).get();
}
```

The culprit is easy to spot---`static_cast` is used to convert `unsigned long long` into the target type, without any range verification:

```
constexpr uint8_t operator"" _u8(unsigned long long val) {
  return uint8_t(static_cast<std::uint8_t>(val));
}
```

A simple solution would be to have something like `return (val > std::numeric_limits<std::uint8_t>::max()) ? throw std::out_of_range(__func__) : uint8_t(static_cast<std::uint8_t>(val));`, but this won't fail at compile-time except in some `constexpr`-using cases.

Using the template form `template<char...> operator"" _u8()` would permit using `static_assert`, but this is a more involved solution that requires parsing the literal manually.

**Comment by foonathan** [comment]
I'll see what I can do.

**Comment by sneves** [comment]
This is great, thanks!

**Comment by sneves** [comment]
OK, not wanting to be too annoying a642d218c189e5a42818fd05a74d93189df5016a does have a few remaining issues:

 - C++14's digit separators are not ignored; e.g., `auto x = 1234'5678_u32` results in a compilation error.
 - Floating-point literals are not entirely rejected; e.g., `auto x = 123.0_i` is rejected at compile-time, but `auto x = 123e1_i` is not, and results in an incorrect value.

**Comment by foonathan** [comment]
No problem, yell at me as match as you want.

I've fixed the issues now.
