### ISSUE TITLE
Public aliases to the type template arguments

### ISSUE THREAD

**Issue by johelegp** [foonathan/type_safe#20]
It'd be nice to have aliases of the template arguments for the types in the library, for all the benefits they provide.

**Comment by foonathan** [comment]
Aliases for what exactly?

**Comment by johelegp** [comment]
For the template arguments of the template classes. Like `strong_typedef` would get a `value_type` for its `T`, which would be useful in a generic context or when `T` is hard to type and there's no readily available alias for it, and maybe a `tag_type` for its `Tag` too.

**Comment by foonathan** [comment]
There is a non-member alias to get the underlying type of strong_typedef, I've deliberately didn't make it a member.

**Comment by johelegp** [comment]
Then I guess `strong_typedef` is fine as it is, but what about the other types? At least the type of the value they wrap should be aliased.

**Comment by foonathan** [comment]
Sorry, I was busy.

As far as I see all the types have aliases?

**Comment by johelegp** [comment]
I am potentially interested in having convenient access to all the template arguments of the relational constraints and `bounded` template classes.
