### ISSUE TITLE
Renaming {Lower,Upper}Constant to {Lower,Upper}Bound

### ISSUE THREAD

**Issue by johelegp** [foonathan/type_safe#22]
99dd91c changed the naming of what was {Lower,Upper}Constant to {Lower,Upper}Bound. I like this new naming because it naturally includes `dynamic_bound` and doesn't exclude them being "constant". The previous naming seemed unnatural when a `Constant` was assigned something named `dynamic`. So I suggest renaming these template arguments.

**Comment by foonathan** [comment]
Agree, fixed.
