### ISSUE TITLE
CMake: External should use current source directory

### ISSUE THREAD

**Issue by mariobadr** [foonathan/type_safe#23]
The dependency on debug_assert in cmake is handled like this:

```cmake
execute_process(COMMAND git submodule update --init -- external/debug_assert
                WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
add_subdirectory(${CMAKE_SOURCE_DIR}/external/debug_assert)
```

However, when adding type_safe as a git submodule to my project, I had to change CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR otherwise the path to external/debug_assert would not be correct. I believe this is the correct fix?

**Comment by foonathan** [comment]
Thank you, typo.
