### ISSUE TITLE
Compile even with "-fno-exception"

### ISSUE THREAD

**Issue by LucaFulchir** [foonathan/type_safe#24]
I am trying to use the library in a project that compiles without exception support.  
The only problem seems to be in **include/type_safe/arithmetic_policy.hpp** where a couple of exceptions are thrown..

My current workaround is adding the following macro in the above file:
<pre>
#if (!defined(__EXCEPTIONS)) && defined(__GNUC__)
    #define TYPE_SAFE_THROW_XOR_ASSERT(x) DEBUG_UNREACHABLE(detail::assert_handler{}, x)
#else
    #define TYPE_SAFE_THROW_XOR_ASSERT(x) throw error (x)
#endif
</pre>
__EXCEPTIONS is defined by gcc and clang, I do not know about other compiles, so I added the __GNUC__ check, too.
Then I changed the throws from:
<pre>
    throw error ("addition will result in overflow") :
</pre>
to:
<pre>
    TYPE_SAFE_THROW_XOR_ASSERT ("addition will result in overflow") :
</pre>

Would you consider adding something similar?

**Comment by sneves** [comment]
FWIW, the equivalent macro in MSVC is [`_CPPUNWIND`](https://msdn.microsoft.com/en-us/library/b0084kay.aspx).

**Comment by foonathan** [comment]
Thank you for the input, I've implemented it.
