### ISSUE TITLE
(Early?) optimizing `constrained_type`

### ISSUE THREAD

**Issue by johelegp** [foonathan/type_safe#27]
I've come up with a few (early?) optimization opportunities for `constrained_type`.

Sometimes we obtain values that are known to meet a constraint, yet if we're wrapping it in a `constrained_type`, we'd have to go through the verifier, increasing the overhead (I don't have measures to backup these claims). A solution for this would be implementing a constructor that doesn't verify the value.

Also, we might want to constraint a value more than an already constrained one. In such a case, it'd be convenient to have a way to specify relations between different `constrained_type`s such that conversion from the less constrained to the more constrained doesn't verify the value.

**Comment by foonathan** [comment]
I don't think that is necessary. I've started playing with it, but just don't think it is feasible.

**Comment by johelegp** [comment]
I guess that's for the best. Even before posting, I realized that the suggestions were somewhat unreasonable. Anyways, thanks for considering them.
