### ISSUE TITLE
an integration test suite could be useful

### ISSUE THREAD

**Issue by xtofl** [foonathan/type_safe#35]
It's great there are already a number of CI jobs defined.  It would be greater still to have some tests that show how an integrator of the library would use it.

This will trap 'physical design' errors like missing/misplaced include files, duplicate definitions, ...

Currently, for instance, including all headers together will result in a double definition

```
cl /I../../include /I../../external/debug_assert include_all.cpp
E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xlocale(341): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
..\..\include\type_safe/strong_typedef.hpp(106): error C2086: 'type_safe::detail::underlying_type = underlying_type_impl<Enum>::type': redefinition
..\..\include\type_safe/compact_optional.hpp(280): note: see declaration of 'type_safe::detail::underlying_type'

```

**Comment by xtofl** [comment]
I thought adding a build step which would compile a number of sources.  The first one could be just 'including' all possible headers.

https://travis-ci.org/xtofl/type_safe/jobs/201140589

**Comment by foonathan** [comment]
Oh, you're right, that's a problem.

**Comment by xtofl** [comment]
If you like, I can start this.  My `cmake` is rusty, however, so I could use some support.  Personally, I was thinking about e.g. a python script creating 'client' environments, checking the compile step, checking the link step, ... even checking that some stuff won't compile, intentionally.

Does that make sense?

**Comment by foonathan** [comment]
I don't know, I don't have experience with something like that either. To prevent that specific kind of problem, I can just create a test file that includes all headers.

**Comment by xtofl** [comment]
For compilation tests, you can (I started this in my fork, and indeed, merging in your fix solved the duplicate definition :) ).

For linking, it's equally important to not have undefined symbols or doubly defined symbols.

Just heard a talk with Mr. Lavavej (cppcast) on how they have a test that prevents e.g. doubly defined linker symbols.

**Comment by pfultz2** [comment]
BTW, the boost cmake modules(that I am currently developing) has the function [`bcm_test_header`](http://bcm.readthedocs.io/en/latest/src/BCMTest.html#bcm-test-header) for testing headers. It also has a `STATIC` option which will test the header across two translation units to avoid doubly-defined symbols.
