### ISSUE TITLE
using old version of debug_assert forces compilation with -std=c++11

### ISSUE THREAD

**Issue by grzebiel** [foonathan/type_safe#39]
After adding type_safe using cmake `add_subdirectory`, currently used version of **debug_assert** does that:

```cmake
if((CMAKE_CXX_COMPILER_ID MATCHES "Clang") OR (CMAKE_CXX_COMPILER_ID MATCHES "GNU"))
    target_compile_options(debug_assert INTERFACE "-std=c++11")
endif()
```
which ends up with `-std=c++11` added to compiler options (after projects own compile options).

There is a [fix](https://github.com/foonathan/debug_assert/commit/c8547057d55a9ee39f63730fb709539d1d071143) for this issue already in the upstream.

**Comment by foonathan** [comment]
That's odd, I thought I fixed that in ac96c309d7f1932bd2b0e0a41cf7b56de5947fca.

**Comment by grzebiel** [comment]
It is, but the next commi t (8364c06) reverted it

**Comment by foonathan** [comment]
Oh, that explained a lot.

**Comment by grzebiel** [comment]
I've created PR to fix it.

**Comment by foonathan** [comment]
Thanks for pointing that out, I've done it now.
