### ISSUE TITLE
hash specialization error

### ISSUE THREAD

**Issue by fisherro** [foonathan/type_safe#4]
This may be entirely user-error, but I’m not figuring it out.

I am using type_safe in my [streams](https://github.com/fisherro/streams) project. When I try to compile, I’m getting this error:

    clang++ -std=c++14 -stdlib=libc++ -I../../GSL -I../../fmt -I../../type_safe/include -I../../debug_assert -I..  -L../../fmt/build/fmt -lfmt  examples.cpp   -o examples
    In file included from examples.cpp:4:
    In file included from ../streams/istream.hpp:5:
    ../../type_safe/include/type_safe/optional.hpp:1039:11: error: explicit
          specialization of non-template class 'hash'
        class hash<type_safe::basic_optional<StoragePolicy>>
              ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [examples] Error 1

Which is strange because hash clearly is a template class.

If I `#if 0` out the entire `namespace std` section in type_safe/optional.hpp, everything compiles fine.

I’m using Clang 3.8.1. (Although I am on Mac OS, I’m not using Apple’s Clang. Just the regular 3.8.1.)

    $ clang++ --version
    clang version 3.8.1 (tags/RELEASE_381/final)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix
    InstalledDir: /opt/local/libexec/llvm-3.8/bin

Any ideas would be appreciated.

**Comment by foonathan** [comment]
Hm, I have no idea.

Adding CI is on my todo list, I'll look into it.

**Comment by fisherro** [comment]
Thanks.

Changing it to struct didn’t help. But taking out just the forward declaration did.

    #if 0
        template <typename T>
        class hash;
    #endif

This I found [this](http://stackoverflow.com/a/3879276/103785) SO answer that appears relevant.

**Comment by foonathan** [comment]
I don't know why I put the declaration there anyway, will remove that one.
