### ISSUE TITLE
Bitwise operators for strong_typedef

### ISSUE THREAD

**Issue by MagnusWestin** [foonathan/type_safe#41]
Hi
Any reason for not including bitwise operators in strong_typedef? I have included your strong_typedef in to a project I'm working on and needed the bitwise stuff. It was easy to add, but I'm a bit curious if there is a reason why its not already in? Is there a problem with that, that I haven't thought of?

Magnus

**Comment by foonathan** [comment]
I was simply too lazy to include them, as my main use of bitwise operators is for bitmasks/flags, and my flag_set takes care of that.

I currently have to rework the operator generation anyway, will include bitwise then as well.

**Comment by foonathan** [comment]
Alright, added them. Let me know if you need anything else.

**Comment by MagnusWestin** [comment]
Cool, I'll update and take a look at it. Thanks :)
