### ISSUE TITLE
Is the difference between gsl::not_null and ts::object_ref?

### ISSUE THREAD

**Issue by sergey-shambir** [foonathan/type_safe#44]
Is there significant difference between both classes? Shouldn't object_ref be named `ts::not_null`?

See also: https://stackoverflow.com/questions/33306553/gslnot-nullt-vs-stdreference-wrappert-vs-t

**Comment by foonathan** [comment]
There is no real difference besides semantics: `ts::object_ref` is a reference to another object, `gls::non_null` is a pointer (i.e. an address) that is not null. Use `ts::object_ref` when you want to reference an object (i.e. most of the time), `gls::non_null` (or the equivalent `ts::constrained_type<T*, ts::constraints::non_null>`) when you want an address that isn't null (result of allocation function, something like `std::destroy()` etc).
