### ISSUE TITLE
type_safe::opt_(c)ref() taking references

### ISSUE THREAD

**Issue by Manu343726** [foonathan/type_safe#45]
I noted that there are no overloads for `opt_(c)ref()` taking references. If I understand the design behind the lib correctly, the idea is that reference forwarding and ownership must me explicit rather than implicit (So that's why a raw pointer overload is provided instead).

When working with optionals I always think of factories like `opt_(c)ref()` as the `Just` and `Nothing` constructors from Haskell's `Maybe` monad, specifically a `opt_(c)ref()` taking lvalue references would model `just`, i.e., constructing a maybe-value from a value.

What do you think?

**Comment by foonathan** [comment]
Yes, I should add those. I plan an improvement of optional anyway.
