### ISSUE TITLE
using xvalue as lvalue

### ISSUE THREAD

**Issue by bricklore** [foonathan/type_safe#46]
I just noticed that in your macro `TYPE_SAFE_DETAIL_MAKE_OP_COMPOUND(...)` you wrote two operators that use an `xvalue` as an `lvalue` (which ofc results in a compile error when used):

```
// ...
/** \exclude */                                                                                \
friend StrongTypedef&& operator Op(StrongTypedef&& lhs, const Other& rhs)                      \
{                                                                                              \
	using type = underlying_type<StrongTypedef>;                                               \
	std::move(static_cast<type&>(lhs)) Op static_cast<const type&>(rhs);                       \
	return std::move(lhs);                                                                     \
}                                                                                              \
/** \exclude */                                                                                \
friend StrongTypedef&& operator Op(StrongTypedef&& lhs, Other&& rhs)                           \
{                                                                                              \
	using type = underlying_type<StrongTypedef>;                                               \
	std::move(static_cast<type&>(lhs)) Op std::move(static_cast<type&>(rhs));                  \
	return std::move(lhs);                                                                     \
}
```

My suggestion is to leave out the `std::move()` from the casted lhs where Op is applied.

**Comment by foonathan** [comment]
Could you provide a minimal example that reproduces the error?

**Comment by bricklore** [comment]
Your use of `std::move` is correct here (contrary to my first supposition).
The problem is actually purely conceptual and ocurrs when writing any assignment-like statements with rvalues on the lhs:

```
MyTypedef a = MyTypedef{1};
std::move(a) += MyTypedef{2};

/* or */
MyTypedef{1} += MyTypedef{2};
```

As rvalue assignment should be an error anyway, your implementation can be considered correct. Nevertheless I find the instanciation of this part of the macro to be conceptually incorrect as the resulting operators may never be used. Maybe I'm missing something but I think these two operators can be removed entirely.

**Comment by foonathan** [comment]
I was thinking about `operator+=` being marked with `&&` (as in: rvalue ref qualifier). Not sure whether that's a thing.
