### ISSUE TITLE
`type_safe::visit` doesn't return references

### ISSUE THREAD

**Issue by SuperV1234** [foonathan/type_safe#48]
Consider the following minimal example:

```cpp
#include <type_safe/variant.hpp>
#include <type_safe/visitor.hpp>

int main()
{
    type_safe::variant<int> x{1};
    &type_safe::visit(
        [](int) -> int& {
            int a;
            return a;
        },
        x);
}
```

It doesn't compile on neither g++7 nor clang++5:

```
error: lvalue required as unary ‘&’ operand
         x);
          ^
```

For some reason the `visit` call is returning `int` instead of `int&`. 

```cpp
type_safe::variant<int> x{1};
decltype(auto) y = type_safe::visit(
    [](int) -> int& {
        int a;
        return a;
    },
    x);

    static_assert(std::is_same_v<decltype(y), int&>); // FAILS
    static_assert(std::is_same_v<decltype(y), int>);  // PASSES
```

**Comment by SuperV1234** [comment]
I think this is happening because [`std::common_type`](http://en.cppreference.com/w/cpp/types/common_type) decays the result type.

**Comment by verri** [comment]
@SuperV1234 just out of curiosity, why would you need `visit` to return a reference or any other non-decayed type?

**Comment by SuperV1234** [comment]
@verri: why not? Here's a weird example from the top of my head:

```cpp
vector<int> user_ids;
vector<int> group_ids;

auto msg_target = get_target_msg();
auto msg_query = get_query_msg();

auto& target = match(msg_target,
    [](UserIds)  -> auto& { return user_ids; },
    [](GroupIds) -> auto& { return group_ids; }
);

apply_query(msg_query, target);
```

You don't know how clients of `visit` are going to use it, there might be a good reason to return a reference.
Also, that's how `std::visit` and `boost::visit` behave, so consistency is a plus.

**Comment by verri** [comment]
Sounds a good reason for me.
