### ISSUE TITLE
Avoiding download of debug_assert

### ISSUE THREAD

**Issue by nicola-gigante** [foonathan/type_safe#49]
How to tell the cmake code to avoid downloading debug_assert.hpp as a git submodule because I already use it in my project and the target already exists?

Doing something like that raises an error:

    add_subdirectory(external/debug_assert)
    add_subdirectory(external/type_safe)

**Comment by foonathan** [comment]
Could you report whether it works in the cmake branch?

**Comment by nicola-gigante** [comment]
Yes, it seems to work!
