### ISSUE TITLE
Assert.hpp line 33: "Conversion from 'long' to 'unsigned int' requires a narrowing conversion."

### ISSUE THREAD

**Issue by NathanMorley** [foonathan/type_safe#51]
I am a new user of type_safe, or at least I would like to be; I am using Microsoft Visual Studio 2017, though when I include seemingly any header file while set in debug configuration (occurs in both 32 and 64 bit configurations), I am met with the error stated in the title. I have included "external/debug_assert" in my project as well. The error appears on line 33 of "assert.hpp", which states the following:

```
inline void on_disabled_exception() noexcept
        {
            struct handler : debug_assert::set_level<1>, debug_assert::default_handler
            {
            };
            DEBUG_UNREACHABLE(handler{},
                              "attempt to throw an exception but exceptions are disabled"); //The error appears on this line.
        }
```
In my test project, this is the only code I have written:
```
#include "type_safe\integer.hpp"

void main() {}
```
I am unsure if I am using the library incorrectly, or if this is an error within the library itself. Any help would be appreciated, thank you.

**Comment by foonathan** [comment]
That's really odd. Could you maybe debug and give me a callstack?

**Comment by NathanMorley** [comment]
Visual Studio 2017 catches the error before running the project, so I suppose it is a compile-time error. The call hierarchy shows that there are no calls **to** "on_disable_exception", though there is a long chain of calls **from** it, seemingly recursive.

![](http://i.imgur.com/tgvuZ46.png)

Actually I just dug around through "debug_assert.hpp" for a while and noticed "struct source_location" has an unsigned member "line_number". Underneath, a macro is defined which inserts the "__LINE__" macro into line_number:
```
//=== source location ===//
    /// Defines a location in the source code.
    struct source_location
    {
        const char* file_name;   ///< The file name.
        unsigned    line_number; ///< The line number.
    };

/// Expands to the current [debug_assert::source_location]().
#define DEBUG_ASSERT_CUR_SOURCE_LOCATION                                                           \
    debug_assert::source_location                                                                  \
    {                                                                                              \
        __FILE__, __LINE__                                                                         \
    }
```
Replacing __LINE__ with `static_cast<unsigned>(__LINE__)` resolves the error and allows me to build and run the project. I am not sure why __LINE__ is of long type, but herein lies the solution.

**Comment by foonathan** [comment]
Oh, sorry, I completely misread your error message.

Could you maybe provide a PR for debug_assert?

**Comment by NathanMorley** [comment]
I do not know what a "PR" is, however I did find and provide a solution for the problem at the end of my last comment.
