### ISSUE TITLE
Flag cannot be cast to bool

### ISSUE THREAD

**Issue by NathanMorley** [foonathan/type_safe#58]
Unsure if the flag is intended to cast to bool or not, but the only workaround is to use `(flag == true)` in cases where you want to check the value of the flag.

**Comment by foonathan** [comment]
It doesn't have implicit to bool conversion by design, and because there is no real way to allow `static_cast<bool>` without also allowing `if (flag)`, I can't add it.

**Comment by NathanMorley** [comment]
Is `if(flag == true)` also the intended method of checking the state of the flag?

**Comment by foonathan** [comment]
Yes.

I designed flag after I had a couple of bugs related to boolean misuse. One of them was a plain `if (foo)` where I wanted to check and reset, i.e. `try_reset`. To make the intentional "only check, don't change", stand out, I require `if (foo == true)`
