### ISSUE TITLE
add inline to this distance function

### ISSUE THREAD

**Issue by viboes** [foonathan/type_safe#65]
https://github.com/foonathan/type_safe/blob/869a14d4348d5e6f71f1f5d7dd36b87cd6794445/include/type_safe/index.hpp#L220

**Comment by viboes** [comment]
Do the same for next and prev

**Comment by foonathan** [comment]
Why? constexpr implies inline

**Comment by viboes** [comment]
Oh, I was not aware of it. Do you have a link?

BTW why 
https://github.com/foonathan/type_safe/blob/869a14d4348d5e6f71f1f5d7dd36b87cd6794445/include/type_safe/index.hpp#L211

is not constexpr?

**Comment by viboes** [comment]
Got it "Yes (§7.1.5/2): "constexpr functions and constexpr constructors are implicitly inline (7.1.2)." "

**Comment by foonathan** [comment]
Missing constexpr on advance is an oversight.
