### ISSUE TITLE
Idea: Safe wrapper with overhead

### ISSUE THREAD

**Issue by chfast** [foonathan/type_safe#66]
Hi there,

@pirapira and me are working on a concept of an integer wrapper called "safe" that extends the values of an integer type with 3 special values: minus infinity (`-Inf`), plus infinity (`+Inf`), invalid (`Invalid`). We want to detect overflows and convert the results to these special values.

Example:

```cpp
bool test(int a, int b) {
  safe<int> x = a;
  safe<int> y = b;
  auto r = x + y;  // This can be normal value, -Inf or +Inf. No UB.
  return r > 0;  // Always valid, because +Inf is greater than 0 and -Inf is less than 0.
}
```

If we can prove this math is consistent, I wanted to ship this as a small header only library. I wander if you would like to include it here instead.

**Comment by foonathan** [comment]
Feel free to publish your own library and let me know when you did it.
