### ISSUE TITLE
type_safe always exposes target debug_assert_example

### ISSUE THREAD

**Issue by ArekPiekarz** [foonathan/type_safe#67]
Adding type_safe library to one's project using CMake always adds target debug_assert_example to the list of all targets. The list is visible for instance in Qt Creator with Ctrl+T shortcut (or clicking in the lower right corner of IDE, above Run icon).

Example:
```
cmake_minimum_required(VERSION 3.0)
project(type-safe-expose-example)
add_subdirectory(external/type_safe)
add_executable(${PROJECT_NAME} "main.cpp")
```

Other libraries that I've seen allow omitting custom library targets by setting definitions, i.e. Catch2 creates example targets only if BUILD_EXAMPLES option is set (and by default it's off). Can you do something similar to not pollute user's project targets? Thanks in advance.

**Comment by foonathan** [comment]
I've pushed a new commit to debug_assert, could you run `git submodule update --remote` and see if it is still shown?

**Comment by ArekPiekarz** [comment]
I can confirm debug_assert_example is no longer shown in my project. Thanks :-)
