### ISSUE TITLE
cast for access to value ref considered problematic

### ISSUE THREAD

**Issue by rollbear** [foonathan/type_safe#7]
When you need to add functionality to a `strong_typedef` it is a bit cumbersome to need to implement it in terms of `static_cast<type&>(*this)`.

```Cpp
  struct name : ts::strong_typedef<name, std::string> {
    using strong_typedef::strong_typedef;
    auto length() const { return static_cast<std::string const&>(*this).length(); }
  };
```

It works, but it's a hurdle which I fear works against the possibility to introduce `strong_typedef` to less skilled developers.

I'm not sure what's a good way to do that, though.

Making the member `value_` protected instead would work, but I don't really like it.

Another option is to use protected inheritance of the type (when possible), but that is also quite ugly.

Yet an option is to add some access function that essentially does the `static_cast<>`, but that pollutes the name space.

I guess there are better ways.

Just wanted to raise the usability concern.

**Comment by foonathan** [comment]
Good point. What about a namespace level `get(*this)`?

**Comment by rollbear** [comment]
This gives access to the raw value also in client code using the strong typedef. Whether this is a good thing or not, is unclear to me.

```Cpp
  name n; // from above

  ts::get(n) = "hello";
```

If this is desirable, then I think the name `get` is not ideal. Perhaps `value_of`?

**Comment by foonathan** [comment]
Client code can do the static cast as well, so get() just provides a short cut.
And as there are probably many incompatible APIs, it is a useful shortcut.

I suggested get() because there are quite a few types providing conversion + get().

**Comment by rollbear** [comment]
Agree

**Comment by rollbear** [comment]
Slow day today, so I can fork and submit a PR if you want me to.

**Comment by foonathan** [comment]
I've already implemented it locally because I needed it for something else, so no need, thanks
