### ISSUE TITLE
Enabled `std::hash` for `strong_typedef`s with `strong_typedef_op::hashable`

### ISSUE THREAD

**Issue by johelegp** [foonathan/type_safe#73]
Greetings.

I just found myself specializing `std::hash` for some strong typedefs of mine which are provided for convenience. I thought it'd be great if the library provided a `strong_typedef_op` that enabled it.

I am available to write it. Would the name in the title be ok? How about copying the hash tests of other library components?

**Comment by foonathan** [comment]
Yes, if you're able to implement it, I'll add it.

However, I don't think you can manage to have a `std::hash` SFINAE based specialization.

**Comment by johelegp** [comment]
You're right. I forgot about the accepted [P0513](https://wg21.link/p0513) and the problem it solved. Now I'm wondering how to implement this in C++11.

**Comment by foonathan** [comment]
What should probably work is having a `hashable` type but a user needs to write a `std::hash` that inherits from it.

**Comment by johelegp** [comment]
Oh, excellent. That would remove as much boilerplate as possible, while still being standard-compliant. I'll now prepare the PR.

**Comment by johelegp** [comment]
I've been checking out the `std::hash` specializations in the library, and they're missing the nested types `result_type` and `argument_type` as required in [N3337](https://wg21.link/n3337). Is it intentional?

**Comment by foonathan** [comment]
According to cppreference, they're deprecated in C++17, so I wouldn't bother.

**Comment by johelegp** [comment]
`hashable` deviates from what the documentation of the `strong_typedef_op` specifies.
```C++
    /// Some operations for [ts::strong_typedef]().
    ///
    /// They all generate operators forwarding to the underlying type,
    /// inherit from then in the typedef definition.
```
It doesn't generate any operators. Since we have to document how to use `hashable`, it would also be the first one to get any explicit documentation. How should I proceed?

**Comment by johelegp** [comment]
`basic_optional` (and maybe `integer` and `floating_point`, which are also parametrized) have `std::hash` specializations even when their wrapped type might not have one, which would violate the `std::hash` requirements. The purpose of having the user specialize a `std::hash` that inherits from `hashable` was to avoid not fulfilling its requirements. But if that doesn't matter, we can have a `std::hash` partial specialization for strong typedefs whose `operator()` SFINAEs based on wether the `StrongTypedef` inherits from `hashable`.

**Comment by foonathan** [comment]
Regarding hashable: You should put it in the top-level namespace I think.

Regarding integer/floating point: I wouldn't worry there.

Regarding optional: the standard library hash disables the specialization by conditionally removing constructor and operator().
