### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by octol** [foonathan/type_safe#77]
I think this is a fantastic library. For us in the corporate world having named released with version numbers makes it much simpler to keep track of our dependencies. Would it be possible to tag a release with the current code as is? There already is an old 0.1, what about marking current HEAD as 0.2?

**Comment by foonathan** [comment]
I can tag a new version but would like to fix #60  and #45 first. You can either wait for two weeks after C++Now for me to do it, or create a PR.

**Comment by foonathan** [comment]
I just went ahead and fixed both issues and released 0.2.

**Comment by octol** [comment]
Thanks!
