### ISSUE TITLE
type_safe::boolean with std::set

### ISSUE THREAD

**Issue by mariobadr** [foonathan/type_safe#8]
Hello,

I am unable to use strong_typedefs with std::set because the STL cannot convert type_safe::boolean to a bool value.

Here is an example of what I am trying to do:

```C++
struct thread_id :
  type_safe::strong_typedef<thread_id, type_safe::integer<uint32_t>>,
  type_safe::strong_typedef_op::equality_comparison<thread_id>,
  type_safe::strong_typedef_op::relational_comparison<thread_id>,
  type_safe::strong_typedef_op::output_operator<thread_id>
{
  using strong_typedef::strong_typedef;
};

int main(int argc, char ** argv)
{
  std::set<thread_id> subscribers;
  thread_id subscriber(0u);

  subscribers.insert(subscriber); // error here

  return 0;
}
```

And here is the error:

> /usr/include/c++/5/bits/stl_function.h: In instantiation of ‘constexpr bool std::less<_Tp>::operator()(const _Tp&, const _Tp&) const [with _Tp = thread_id]’:
> /usr/include/c++/5/bits/stl_tree.h:1810:11:   required from ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_unique_pos(const key_type&) [with _Key = thread_id; _Val = thread_id; _KeyOfValue = std::_Identity<thread_id>; _Compare = std::less<thread_id>; _Alloc = std::allocator<thread_id>; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::key_type = thread_id]’
> /usr/include/c++/5/bits/stl_tree.h:1863:28:   required from ‘std::pair<std::_Rb_tree_iterator<_Val>, bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_insert_unique(_Arg&&) [with _Arg = const thread_id&; _Key = thread_id; _Val = thread_id; _KeyOfValue = std::_Identity<thread_id>; _Compare = std::less<thread_id>; _Alloc = std::allocator<thread_id>]’
> /usr/include/c++/5/bits/stl_set.h:485:29:   required from ‘std::pair<typename std::_Rb_tree<_Key, _Key, std::_Identity<_Key>, _Compare, typename __gnu_cxx::__alloc_traits<_Alloc>::rebind<_Key>::other>::const_iterator, bool> std::set<_Key, _Compare, _Alloc>::insert(const value_type&) [with _Key = thread_id; _Compare = std::less<thread_id>; _Alloc = std::allocator<thread_id>; typename std::_Rb_tree<_Key, _Key, std::_Identity<_Key>, _Compare, typename __gnu_cxx::__alloc_traits<_Alloc>::rebind<_Key>::other>::const_iterator = std::_Rb_tree_const_iterator<thread_id>; std::set<_Key, _Compare, _Alloc>::value_type = thread_id]’
> /home/badrmari/Projects/phd/sim-sync/src/sim-sync-cl/main.cpp:21:32:   required from here
> /usr/include/c++/5/bits/stl_function.h:387:22: error: cannot convert ‘type_safe::boolean’ to ‘bool’ in return
>        { return __x < __y; }

Is there a way to fix this with an additional strong_typedef_op? Or is strong_typedef incompatible with STL containers that need to do comparisons?

(Using gcc 5.4.0)

**Comment by foonathan** [comment]
`ts::boolean` does not convert to `bool` by design, but the `ts::strong_typedef_op::*_comparison` functions return `ts::boolean` by default, thus the error in `std::less`. And I think `std::less` return type must be implicitly convertible to `bool`, so must not be `ts::boolean`.

You can fix it by changing the return type of the generated `ts::strong_typedef_op::*_comparison` operations, there is a third template parameter: `ts::strong_typedef_op::equality_comparison<thread_id, bool>`. Then it will return plain `bool`.

PS: I see you are using `ts::integer<std::uint32_t>`. There is also a convenience typedef available in `types.hpp`, so you can write `ts::uint32_t`. Then you can also use `42_u32` literal to create an object of the right size because the above code would fail to compile on platforms where `unsigned` is bigger than `std::uint32_t` due to a possible narrow conversion.

**Comment by mariobadr** [comment]
Thanks, I managed to get it to work by setting the relational_comparison to return a plain bool (I didn't need to change equality comparison in this specific case). What exactly am I losing by making this change (in terms of type safety)? Is my understanding correct that: this means the value returned by a relational comparison is bool, and thus it can be compared to a non-boolean primitive?

Thank you for letting me know about the convenience typedef. I'll switch it up in my codebase :)

**Comment by foonathan** [comment]
Yes, it is plain old bool, so you can do everything you can do with a regular bool (arithmetic, comparisons with everything etc.).

A more type safe version would probably be a std::less specialization/custom comparator that uses the type safe operator< and casts to bool.

**Comment by mariobadr** [comment]
Hm, would it make sense for type_safe to include a custom comparator for ts::boolean? Then I could type something like:

`std::set<thread_id, type_safe::boolean_comparator> subscribers;`

and not have to change the relational_comparison_op to bool?

**Comment by foonathan** [comment]
Yes, I could add something like that.

**Comment by mariobadr** [comment]
Awesome, thanks for the great library :)

**Comment by foonathan** [comment]
I've added `ts::less` etc. to `boolean.hpp`, you can use that.
