### ISSUE TITLE
Any interest in arithmetical comparison of signed and unsigned integers?

### ISSUE THREAD

**Issue by kyku** [foonathan/type_safe#80]
It is quite common to see mixed comparisons between unsigned and signed variables spread around many code bases that I work with. The integer conversion rules of such can yield arithmetically incorrect results. Currently, type_safe seems to disable such comparisons, but it I thought it could provide either explicit functions to perform them or even allow them implicitly "under the hood" by default, provided the results are arithmetically correct. 

An example pseudo code:
```
bool arith_lt(i32 i, u32 u) { // lt => less than
  return i < 0 || u32(i) < u;
}

```
What is your opinion?

**Comment by foonathan** [comment]
I think something like that is definitely useful, especially since the built-in comparisons are going to behave like that as well.

I'm not sure whether I can simply use the operator overloads for that.

**Comment by philipp2100** [comment]
> I think something like that is definitely useful, especially since the built-in comparisons are going to behave like that as well.

What do you mean by that? `-1 < 1U == false`!

**Comment by Neargye** [comment]
maybe "safe integral comparisons" like http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0586r2.html

**Comment by foonathan** [comment]
I don't have the time to implement something like that at the moment, but I would happily merge a PR if anyone is willing to do so!
