### ISSUE TITLE
Possibly unexpected behaviour

### ISSUE THREAD

**Issue by Crzyrndm** [foonathan/type_safe#83]
Note: this isn't tested, nevermind proven (I was only reading the file to compare the array_ref implementation with something I've been using). Just looks similar to a bug I've had previously 

https://github.com/foonathan/type_safe/blob/master/include/type_safe/reference.hpp#L401-L408
Hypothesis: If any of the additional args are moved by std::forward, only the first element is going to see the expected arguments (i.e. a "std::move"ed unique_ptr would be consumed by the first element of the array, all subsequent elements would see a moved from unique_ptr (most likely nullptr))

I don't believe this would be the expected behaviour from a naive use of [ts::with]

```
void func(int&, unique_ptr<int>);
array_ref<int> ref(...);
 // forwarding the unique_ptr here is a move, only the first element of ref will see the initial value
with(ref, func, make_unique(new int(1)));
```

**Comment by johelegp** [comment]
You are right. The documentation isn't clear on various things:
- The order of traversal of the array.
- Whether the function object and its intended arguments are moved or forwarded at some point.

With such a simple description, I'd expect [`0`, `size()`) order of traversal and no move or forwarding of the additional arguments. YMMV.

There's also a (possible) bug in the implementation. When `XValue` is true, `elem` is initialized from the moved from elements of the array, [according to its documentation](https://github.com/foonathan/type_safe/blob/b645fe4435b284700e433abada9582842b7566f2/include/type_safe/reference.hpp#L284). However, an lvalue is always being passed to the function object invocation.

**Comment by foonathan** [comment]
Thank your noticing it, fixed.
