### ISSUE TITLE
tagged_union with incomplete types?

### ISSUE THREAD

**Issue by Hopobcn** [foonathan/type_safe#87]
A `ts::tagged_union` holds the storage of `ts::variant` but `std::is_trivially_copyable` and the `sizeof` operation from `ts::detail::aligned_union` prevents passing incomplete types.

Do you think that implementing the `storage_` as a `void*` for incomplete types would be a good idea?
Do you know of other `variant` implementations that allow incomplete types?

PD: Great library! A true piece of art :+1:

**Comment by foonathan** [comment]
This would require dynamic allocation, which I don't want.

I don't know any variant implementation which does support it, if you really need it, you can implement an `incomplete_holder` class:

```cpp
template <typename T>
class incomplete_holder
{
    std::unique_ptr<T> ptr_;
public:
    // the interface you want
};
```

And then store that inside the variant.
