### ISSUE TITLE
CMake Install

### ISSUE THREAD

**Issue by pr0g** [foonathan/type_safe#88]
Hi there,

I've been doing a bunch of investigation into modern CMake approaches when it comes to library design and `type_safe` looks like an excellent example of this.

I may well be at fault here and may not be understanding something correctly but I've run into an issue when attempting to install the `type_safe` library and use it via `find_package` (I may be mistaken that this is possible/advised?).

It appears as though `type_safe-config.cmake` is not installed to the correct location.

The steps I took are as follows:

1. Cloned `type_safe` repo to `<my-project>/external/type_safe`
2. Created a `build` folder there (`<my-project>/external/type_safe/build`)
3. Ran `cmake ..` to generate the build files
4. I then ran `cmake --build . --target install`
5. After running this, I get this output:
```
    -- Install configuration: "" (missing config file here?)
    -- Up-to-date: /usr/local/include/type_safe
    -- ... etc. (all other type_safe files...)
```
6. I have a crazy simple project attempting to consume the library, the `CMakeLists.txt` file looks like this:

```
cmake_minimum_required(VERSION 3.8)

find_package(type_safe REQUIRED)

add_executable(test main.cpp)

target_compile_features(test PRIVATE cxx_variadic_templates)
target_link_libraries(test PUBLIC type_safe)
```
7. However when I run `cmake ..`, I get this error:

```
By not providing "Findtype_safe.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "type_safe", but CMake did not find one.

  Could not find a package configuration file provided by "type_safe" with
  any of the following names:

    type_safeConfig.cmake
    type_safe-config.cmake

  Add the installation prefix of "type_safe" to CMAKE_PREFIX_PATH or set
  "type_safe_DIR" to a directory containing one of the above files.  If
  "type_safe" provides a separate development package or SDK, be sure it has
  been installed.
```
8. If I instead however do this in the `CMakeLists.txt` file:

```
cmake_minimum_required(VERSION 3.8)

add_subdirectory(external/type_safe) # not using find_package()

add_executable(test main.cpp)

target_compile_features(test PRIVATE cxx_variadic_templates)
target_link_libraries(test PUBLIC type_safe)
```

everything builds correctly and I can use the library. My `main.cpp` looks like this:

```
#include <stdio.h>

#include "type_safe/integer.hpp"

int main(int argc, char** argv)
{
    type_safe::integer<int> answer = 42;
    printf("The answer is: %d\n", answer.get());

    return 0;
}
```

Essentially my basic question is should I be able to use `type_safe` with the `find_package()` mechanism in CMake, or should I just use the `add_subdirectory` approach?

I'm interested in writing my own header only library and want to make sure I better understand the modern CMake approaches (INSTALL/EXPORT/Packages etc..) I have to admit I find it all quite confusing :( I read your blog entry https://foonathan.net/blog/2016/03/03/cmake-install.html which was super interesting but to the uninitiated is still quite overwhelming :P.

Thank you very much for your time,

All the best,

Tom

**Comment by pr0g** [comment]
Hi Jonathan,

Thank you for getting back to me, I appreciate you taking the time!

Hmm I do believe I've installed `debug_assert` (that is the git submodule that gets installed as part of `type_safe`?) I'm pretty sure that's there, though I may be mistaken.

It looks to me like `find_package` isn't working as the `.make` file does not get installed to the correct location. My reason for attempting to avoid `add_directory` was to try and follow the 'Modern CMake' advice, just wanted to try and make it work as in theory it should. I'll see if I can also dig into it some more and see if I can find what's wrong.

Any other suggestions please give me a shout,

Thanks again!


Tom

**Comment by foonathan** [comment]
Okay, I've tested it myself, for me install and `find_package()` works flawlessly. It's probably a MacOS issue?

**Comment by pr0g** [comment]
Hmm interesting, what platform are you building on? Could you let me know the commands you ran? Would be super helpful to replicate. Thanks!

**Comment by pr0g** [comment]
Awesome thank you, I'll have a futz about and see if I can figure out why it isn't working on macOS.

Appreciate you trying to help,

Thanks for your time!

(I'll close for now and if I have a breakthrough I'll let you know :))

**Comment by pr0g** [comment]
Hello again!

Good news! I've got it to work! 🍾 

I started again from scratch and followed the exact steps you outlined and got the same error I reported. I had a little look at the `CMakeLists.txt` file for `type_safe` and as a test removed the line: `if(TYPE_SAFE_HAS_IMPORTED_TARGETS)` (and the corresponding `endif()`). After I did this and ran `cmake .. && make install`, the library installed successfully!:

<img width="624" alt="screen shot 2018-08-23 at 22 02 13" src="https://user-images.githubusercontent.com/1136625/44551823-38e31b80-a720-11e8-84c9-103abd81ccf6.png">

I then jumped back to my project and ran `cmake ..` from the build directory, but got the same issue I was seeing before, only this time with `debug_assert` instead of `type_safe`:

<img width="962" alt="screen shot 2018-08-23 at 22 04 06" src="https://user-images.githubusercontent.com/1136625/44551913-78aa0300-a720-11e8-9f85-f517b18d0e51.png">

I navigated to to the `debug_assert` directory, created a build folder and ran `cmake .. && make install` and that worked fine first time!

<img width="662" alt="screen shot 2018-08-23 at 22 05 56" src="https://user-images.githubusercontent.com/1136625/44552018-ca528d80-a720-11e8-8c94-3a07890e1bd9.png">

I then jumped back to my project again, ran `cmake ..`, and hey presto! Everything built and ran :)

I'm not sure how one should use `TYPE_SAFE_HAS_IMPORTED_TARGETS` or when/where it should be set - I'm also not sure why this worked on Linux without this being removed. If you could shed any light on this I would be very grateful. I'm still a 'Modern CMake' noob but I think I'm slowly understanding it a little better. It also would be nice if `debug_assert` could get installed automatically somehow when you install `type_safe` but that could maybe be explained in the docs/readme.

Anyway thanks again for your help and glad I was able to get it working!

Cheers,


Tom

**Comment by pr0g** [comment]
You'll be happy to know this example also works on Windows using Visual Studio 2017 (albeit with needing administrative privileges for the INSTALL steps).

`debug_assert` and `type_safe` end up in ` C:/Program Files (x86)/DEBUG_ASSERT/...` and  `C:/Program Files (x86)/TYPE_SAFE/...` respectively. I was able to compile, link and run my executable using `type_safe` and `find_package`.

I didn't check but I was wondering if there is a way to override the default install location?

Very cool stuff! :)

Cheers,


Tom

**Comment by foonathan** [comment]
> I'm not sure how one should use TYPE_SAFE_HAS_IMPORTED_TARGETS or when/where it should be set - I'm also not sure why this worked on Linux without this being removed. If you could shed any light on this I would be very grateful. I'm still a 'Modern CMake' noob but I think I'm slowly understanding it a little better. It also would be nice if debug_assert could get installed automatically somehow when you install type_safe but that could maybe be explained in the docs/readme.

Ahh, I had debug_assert already installed, that's why it was working for me, sorry about that. I didn't write the install code @pfultz2 did, and I'm not sure whether installing it automatically is possible.

> didn't check but I was wondering if there is a way to override the default install location?

You can change this CMake variable: https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html

**Comment by pr0g** [comment]
Ahh I see - cool.

I ran through the process again, this time installing `debug_assert` ahead of time and it worked correctly.

Cool thanks for the link, I'll have a play around with changing the CMAKE_INSTALL_PREFIX path.

Cheers!


Tom
