### ISSUE TITLE
Documentation enhancements regarding differences to other libraries and general concepts

### ISSUE THREAD

**Issue by FlorianWolters** [foonathan/type_safe#89]
I suggest adding a section to the `README.md` that defines the unique features (regarding type-safe facilities) of `foonathan/type_safe` and differences to other existing *Strong Type* implementations.

I am aware of the following libraries related to the topic of strong tpying in C++:

* [Boost.Units](https://www.boost.org/doc/libs/1_68_0/doc/html/boost_units.html)
* [`BOOST_STRONG_TYPEDEF`](https://www.boost.org/doc/libs/1_68_0/libs/serialization/doc/strong_typedef.html) (part of Boost.Serialization)
* [martinmoene/PhysUnits-CT-Cpp11](https://github.com/martinmoene/PhysUnits-CT-Cpp11)
* [joboccara/NamedType](https://github.com/joboccara/NamedType)
* [rollbear/strong_type](https://github.com/rollbear/strong_type)
* [mariobadr/strong](https://github.com/mariobadr/strong)
* [opaque_typedef](https://sourceforge.net/projects/opaque-typedef)

There has been a lot of writing related to the topic (the last "wave" appeared two years ago), so I think such information (and general information as well) would help users to select a library.

Here is a list of some articles that appeared on the WWW regarding the topic.

* [Enhance type safety using Opaque Typdefs aka phantom type](http://nullptr.nl/2018/02/phantom-types)
* [Strong types for strong interfaces](https://www.fluentcpp.com/2016/12/08/strong-types-for-strong-interfaces)
* [Use Stronger Types!](https://arne-mertz.de/2016/11/stronger-types)
* [Tutorial: Emulating strong/opaque typedefs in C++](https://foonathan.net/blog/2016/10/19/strong-typedefs.html)
* [Type safe - Zero overhead utilities for more type safety](https://foonathan.net/blog/2016/10/11/type-safe.html)
* [Getting Strongly Typed Typedefs Using Phantom Types](https://blog.demofox.org/2015/02/05/getting-strongly-typed-typedefs-using-phantom-types/)
* [Type safe handles in C++](http://www.ilikebigbits.com/2014_05_06_type_safe_handles.html)
* [True typedefs](http://www.drdobbs.com/true-typedefs/184401633)

I also think *Strong Typedef* (`strong_typedef`) is a suboptimal name, since it really does introduce a new type (see [Perennial impossibilities of C++](https://quuxplusone.github.io/blog/2018/06/12/perennial-impossibilities/#strong-typedefs)).

Using the term *Named Type* (`named_type`) (as in proposal [P0027R0: Named Typed](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0027r0.pdf)) would be better, imo. I think the common understanding of a named type is that it is an explicitly defined type with a name. Alternatively using *Strong Type* (`strong_type`) would also be better, imo.

Maybe it also makes sense to describe the following terms so that an user of the library can understand the concepts better and identify differences:

* Named Type
* Opaque Typedef
* Phantom Type
* Strong Type
* Strong Typedef
* Strongly Typed Typedef
* Type Alias
* Typedef

For me, *Opaque Typedef*, *Strong Typedef*, *Strongly Typed Typedef* are the same.

I've just started playing around with strong typing in C++, but I can see that others may have problems regarding all the terms.

**Comment by foonathan** [comment]
I've already linked my blog post about strong typedefs in the readme, I think that's sufficient.

> Using the term Named Type (named_type) (as in proposal P0027R0: Named Typed) would be better, imo. I think the common understanding of a named type is that it is an explicitly defined type with a name. Alternatively using Strong Type (strong_type) would also be better, imo.

I won't change it here, but maybe if/when I submit a strong/opaque/named type library to Boost (see also #82).
