### ISSUE TITLE
function_ref fails to compile on MSVC 2019 Preview

### ISSUE THREAD

**Issue by dvirtz** [foonathan/type_safe#92]
Just for reference. I've opened a bug for MSVC:
https://developercommunity.visualstudio.com/content/problem/409314/1920-fails-to-compile-a-legitimate-code-with-use-o.html

**Comment by foonathan** [comment]
As it's a preview, I am too lazy to workaround (nor can verify that workaround) easily. Let me know if the issue isn't fixed on their end.

**Comment by NN---** [comment]
There is no fix from Microsoft, can you make a workaround ?

**Comment by foonathan** [comment]
The godbolt link in the issue seems to work: https://gcc.godbolt.org/z/PU7kGh

As I don't have access to the compiler it is impossible for me to figure out what I need to change. Could you try and get me a godbolt link that doesn't work? Otherwise, I can't help you.

**Comment by NN---** [comment]
Oh, it is a regression !
It does compile in 19.16 but doesn't with 19.24.

https://gcc.godbolt.org/z/akEeJv
