### ISSUE TITLE
 Why includes that require -I flag?

### ISSUE THREAD

**Issue by brenoguim** [foonathan/type_safe#98]
I noticed in the header files, say `strong_typedef.hpp`, that other library files are included like:

```cpp
#include <type_safe/config.hpp>
```

That works because I suppose the expected usage of the library is to do:
```cpp
g++ -I <project_root>/thirdparty/type_safe/include
```
While that is very reasonable, sometimes large codebases struggle with cluncky old build systems, and the task of passing `-I` (automatically and transitively) can be hard.

That being said, I'd like to know if you see drawbacks in doing relative includes:
```cpp
#include "config.hpp"
```
That would allow people to use the library by including the full path:
```cpp
#include "thirdparty/type_safe/include/type_safe/strong_typedef.hpp"
```
That may seem ugly but is also extremely "drop-in" :) And, of course, would still work for people doing `-I`.

I know the rules for including files are not well agreed upon (and implementation defined?), so I may very well be missing something.

**Comment by foonathan** [comment]
I plan on putting the strong typedefs into a standalone library eventually anway, so I'm closing this for now.
